# Site settings
title: Rydzowe Wzgórze
email: tabue.piotr@gmail.com
url: https://rydzowe-wzgorze.github.io
description: Domek całoroczny do wynajęcia w okolicy Koleczkowa (wojwództwo pomorskie).

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Rydzowe Wzgórza - Taube Piotr
  location: Lokalizacja
  social: Odezwij się

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Facebook
    url: https://www.facebook.com/rydzowewzgorze

# Postal address (add as many lines as necessary)
address:
  - line: Bożańska 4
  - line: Koleczkowo 84-209
  - line: powiat wejherowski, województwo pomorskie

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

gallery:
  - image: IMG_0307.jpg
  - image: IMG_0313.jpg
  - image: IMG_0316.jpg
  - image: IMG_0327.jpg
  - image: IMG_0341.jpg
  - image: IMG_0520.JPG
  - image: IMG_0532.JPG
  - image: IMG_0546.JPG
  - image: IMG_0549.JPG
  - image: IMG_0579.JPG
  - image: IMG_0580.JPG
  - image: IMG_0782.JPG
  - image: IMG_0799.JPG
  - image: IMG_0800.JPG
  - image: IMG_1249.JPG
  - image: IMG_1251.JPG
  - image: IMG_1260.JPG
  - image: IMG_1265.JPG
  - image: IMG_1268.JPG
  - image: IMG_1301.jpg
  - image: IMG_1302.jpg
  - image: IMG_1303.jpg
  - image: IMG_1304.jpg
  - image: IMG_1305.jpg
  - image: IMG_1306.jpg
  - image: IMG_1308.jpg
  - image: IMG_1309.jpg
  - image: IMG_1310.jpg
  - image: IMG_1311.jpg
  - image: IMG_1312.jpg
  - image: IMG_1314.jpg
  - image: IMG_1315.jpg
  - image: IMG_1317.jpg
  - image: IMG_1318.jpg
  - image: IMG_1319.jpg
  - image: IMG_1320.jpg
  - image: IMG_1321.jpg
  - image: IMG_1322.jpg
  - image: IMG_1323.jpg
  - image: IMG_1324.jpg
  - image: IMG_1325.jpg
  - image: IMG_1326.jpg
  - image: IMG_1329.jpg
  - image: IMG_1330.jpg
  - image: IMG_1331.jpg
  - image: IMG_1334.jpg
  - image: IMG_1335.jpg
  - image: IMG_1339.jpg
  - image: IMG_1340.jpg
  - image: IMG_1342.jpg
  - image: IMG_1343.jpg
  - image: IMG_1345.jpg
  - image: IMG_1346.jpg
  - image: IMG_1347.jpg
  - image: IMG_1349.jpg
  - image: IMG_1350.jpg
  - image: IMG_1351.jpg
  - image: IMG_1353.jpg
  - image: IMG_1354.jpg
  - image: IMG_1355.jpg
  - image: IMG_1357.jpg
  - image: IMG_1358.jpg
  - image: IMG_3245.JPG
  - image: IMG_3271.JPG
  - image: IMG_3508.JPG
  - image: IMG_3527.JPG
  - image: siema.jpg
